version: '2.3'

services:
    files:
        container_name: "rDrama"
        build:
            context: .
        volumes:
            - "./:/service"
        env_file: env
        environment:
            - DATABASE_URL=postgresql://postgres@postgres:5432
            - REDIS_URL=redis://redis
        links:
            - "redis"
            - "postgres"
        ports:
            - "5000:5000"
        depends_on:
            - redis
            - postgres
            - nginx

    redis:
        image: redis
        ports:
            - "6379:6379"

    postgres:
        image: postgres
        command: ["postgres", "-c", "log_statement=all"]
        volumes:
            - "./schema.sql:/docker-entrypoint-initdb.d/00-schema.sql"
            - "./seed-db.sql:/docker-entrypoint-initdb.d/10-seed-db.sql"
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
        ports:
            - "5432:5432"

    nginx:
        image: nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx.txt:/etc/nginx/conf.d/default.conf
            - ./nginx-serve-static.txt:/etc/nginx/includes/serve-static
