export enum CasinoHandlers {
  // Outgoing
  UserKickedOwnClient = "user-kicked-own-client",
  UserSentMessage = "user-sent-message",
  UserReactedToMessage = "user-reacted-to-message",
  UserEditedMessage = "user-edited-message",
  UserDeletedMessage = "user-deleted-message",
  UserConversed = "user-conversed",
  UserStartedGame = "user-started-game",
  UserQuitGame = "user-quit-game",
  UserPlayedSlots = "user-played-slots",
  UserPlayedRoulette = "user-played-roulette",
  UserPlayedBlackjack = "user-played-blackjack",
  UserPlayedRacing = "user-played-racing",

  // Incoming
  Disconnect = "disconnect",
  StateChanged = "state-changed",
  ErrorOccurred = "error-occurred",
  JoinedAgain = "joined-again",
  Refresh = "refresh",
  InitialStateProvided = "initial-state-provided",
  ConfirmationReceived = "confirmation-received",
  ConversationUpdated = "conversation-updated",
  ReactionUpdated = "reaction-updated",
  FeedUpdated = "feed-updated",
  GameUpdated = "game-updated",
  GamesUpdated = "games-updated",
  LeaderboardUpdated = "leaderboard-updated",
  MessageUpdated = "message-updated",
  MessageDeleted = "message-deleted",
  SessionUpdated = "session-updated",
  UserUpdated = "user-updated",
}

export enum CasinoClientActions {
  INITIAL_STATE_PROVIDED = "INITIAL_STATE_PROVIDED",
  USER_UPDATED = "USER_UPDATED",
  MESSAGE_UPDATED = "MESSAGE_UPDATED",
  MESSAGE_DELETED = "MESSAGE_DELETED",
  CONVERSATION_UPDATED = "CONVERSATION_UPDATED",
  REACTION_UPDATED = "REACTION_UPDATED",
  FEED_UPDATED = "FEED_UPDATED",
  LEADERBOARD_UPDATED = "LEADERBOARD_UPDATED",
  GAME_UPDATED = "GAME_UPDATED",
  GAMES_UPDATED = "GAMES_UPDATED",
  SESSION_UPDATED = "SESSION_UPDATED",
}
